services:
  app1:
    build: .
    container_name: node_app_1
    environment:
      - APP_NAME="Nginx-Docker App 1"
    ports:
      - "3001:3000"

  app2:
    build: .
    container_name: node_app_2
    environment:
      - APP_NAME="Nginx-Docker App 2"
    ports:
      - "3002:3000"

  app3:
    build: .
    container_name: node_app_3
    environment:
      - APP_NAME="Nginx-Docker App 3"
    ports:
      - "3003:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
