services:
  app1:
    build: .
    container_name: node_app_1
    environment:
      - APP_NAME="Nginx-Docker App 1"
    networks:
      - app_network

  app2:
    build: .
    container_name: node_app_2
    environment:
      - APP_NAME="Nginx-Docker App 2"
    networks:
      - app_network

  app3:
    build: .
    container_name: node_app_3
    environment:
      - APP_NAME="Nginx-Docker App 3"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    entrypoint: ["/bin/sh", "-c", "/etc/nginx/generate_cert.sh && nginx -g 'daemon off;'"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl
      - ./generate_cert.sh:/etc/nginx/generate_cert.sh:ro
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
